---
functional:
  - Пользователь должен иметь возможность выбрать уровень сложности и тип игрока
  - Пользователь должен иметь возможность выбора времени решения
  - Пользователь должен иметь возможность войти в систему, используя свое имя пользователя и пароль
  - Пользователь должен иметь возможность регистрации
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен быть интуитивно-понятным и удобным в использовании
  - При обновлении страницы язык должен оставаться выбраным
  - Сайт по умолчанию должен иметь язык страны пользователя
  - Пользователь должен иметь возможность прохождения без регистрации пользователя
